spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/presentable
    username: aleksey
    password: as180401
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect